using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DearSanta.Models
{
    public static class DbInitializer
    {
        public static void Seed(AppDbContext context)
        {
            if (!context.Gifts.Any())
            {
                context.AddRange
                (
                    new Gift { Name = "Socks", Price = 10.99, ShortDesc = "You'll love it!", LongDesc = "A sock is an item of clothing worn on the feet and often covering the ankle or some part of the calf. Some type of shoe or boot is typically worn over socks. In ancient times, socks were made from leather or matted animal hair. In the late 16th century, machine-knit socks were first produced. Until 1800 both hand knitting and machine knitting were used to produce socks, but after 1800, machine knitting became the predominant method.", ImageUrl = "/images/Details/socks.jpg", ThumbnailUrl = "/images/ChristmasGift.jpg" },
                    new Gift { Name = "Legos", Price = 22.99, ShortDesc = "Simple, yet fun.", LongDesc = "is a line of plastic construction toys that are manufactured by The Lego Group, a privately held company based in Billund, Denmark. The company's flagship product, Lego, consists of colourful interlocking plastic bricks accompanying an array of gears, figurines called minifigures, and various other parts. Lego pieces can be assembled and connected in many ways to construct objects including vehicles, buildings, and working robots. Anything constructed can then be taken apart again, and the pieces used to make other objects.", ImageUrl = "/images/Details/lego.jpg", ThumbnailUrl = "/images/ChristmasGift.jpg" },
                    new Gift { Name = "Action Figure", Price = 9.99, ShortDesc = "Perfect Christmas present.", LongDesc = "An action figure is a doll or basically a poseable character doll, made of plastic or other materials, and often based upon characters from a film, comic book, military, video game, or television program, fictional or historical. These dolls are usually marketed toward boys and adult collectors.", ImageUrl = "/images/Details/actionfig.jpg", ThumbnailUrl = "/images/ChristmasGift.jpg" },
                    new Gift { Name = "BB-gun", Price = 56.99, ShortDesc = "Use with caution.", LongDesc = "BB guns are a type of air guns designed to shoot metallic ball projectiles called BBs — metal balls approximately the same size as the 0.180 inches (4.6 mm) BB lead birdshots. Modern BB guns usually have a barrel with a bore caliber of 4.5 mm (0.177 in) and are available in many varieties. These guns usually use steel BB shots, either zinc- or copper-plated to resist corrosion, and measuring 4.3 to 4.4 mm (0.171 to 0.173 in) in diameter and 0.33 to 0.35 g (5.1 to 5.4 gr) in weight.", ImageUrl = "/images/Details/bbgun.jpg", ThumbnailUrl = "/images/ChristmasGift.jpg" },
                    new Gift { Name = "Lightsaber", Price = 150.00, ShortDesc = "Do it.", LongDesc = "A lightsaber is a fictional energy sword featured in the Star Wars universe. A typical lightsaber is depicted as a luminescent blade of magnetically contained plasma about 3 feet (91 cm) in length emitted from a metal hilt around 10.5 inches (27 cm) in length. The lightsaber is the signature weapon of the Jedi Order and their Sith counterparts, both of whom can use them for melee combat, or to deflect blaster bolts.", ImageUrl = "/images/Details/ligs.jpg", ThumbnailUrl = "/images/ChristmasGift.jpg" },
                    new Gift { Name = "Toy Dinosaur", Price = 14.99, ShortDesc = "Prehistorc toys.", LongDesc = "Suitable for kids ages 3 years and up, kids will enjoy hours of Imaginative Play with realistic-looking. Ideal christmas gift or party favor for a dinosaur themed birthday party", ImageUrl = "/images/Details/dino.jpg", ThumbnailUrl = "/images/ChristmasGift.jpg" },
                    new Gift { Name = "Football", Price = 9.99, ShortDesc = "Fun to play around with others.", LongDesc = "A football is a ball inflated with air that is used to play one of the various sports known as football. In these games, with some exceptions, goals or points are scored only when the ball enters one of two designated goal-scoring areas; football games involve the two teams each trying to move the ball in opposite directions along the field of play.", ImageUrl = "/images/Details/ball.jpg", ThumbnailUrl = "/images/ChristmasGift.jpg" },
                    new Gift { Name = "Video Game", Price = 60.00, ShortDesc = "Time passes quickly with these.", LongDesc = "A video game is an electronic game that involves interaction with a user interface to generate visual feedback on a video device such as a TV screen or computer monitor. The word video in video game traditionally referred to a raster display device, but as of the 2000s, it implies any type of display device that can produce two- or three-dimensional images.", ImageUrl = "/images/Details/videogames.jpg", ThumbnailUrl = "/images/ChristmasGift.jpg" },
                    new Gift { Name = "Painting", Price = 255.99, ShortDesc = "Pieces of art.", LongDesc = "Paintings can be naturalistic and representational (as in a still life or landscape painting), photographic, abstract, narrative, symbolistic (as in Symbolist art), emotive (as in Expressionism), or political in nature (as in Artivism). n art, the term painting describes both the act and the result of the action. The support for paintings includes such surfaces as walls, paper, canvas, wood, glass, lacquer, pottery, leaf, copper and concrete. ", ImageUrl = "/images/Details/paintings.jpg", ThumbnailUrl = "/images/ChristmasGift.jpg" },
                    new Gift { Name = "Sandals", Price = 13.99, ShortDesc = "Will match perfectly with socks.", LongDesc = "Sandals are an open type of footwear, consisting of a sole held to the wearer's foot by straps going over the instep and, sometimes, around the ankle. Sandals can also have a heel. While the distinction between sandals and other types of footwear can sometimes be blurry, the common understanding is that a sandal leaves all or most of the foot exposed. People may choose to wear sandals for several reasons, among them comfort in warm weather, economy and as a fashion choice.", ImageUrl = "/images/Details/sandal.jpg", ThumbnailUrl = "/images/ChristmasGift.jpg" },
                    new Gift { Name = "Walkie-Talkie", Price = 4.99, ShortDesc = "Long distance talking device", LongDesc = "Typical walkie-talkies resemble a telephone handset, with a speaker built into one end and a microphone in the other (in some devices the speaker also is used as the microphone) and an antenna mounted on the top of the unit. They are held up to the face to talk. A walkie-talkie is a half-duplex communication device. Multiple walkie-talkies use a single radio channel, and only one radio on the channel can transmit at a time, although any number can listen. ", ImageUrl = "/images/Details/walktalk.jpg", ThumbnailUrl = "/images/ChristmasGift.jpg" },
                    new Gift { Name = "Camera", Price = 19.99, ShortDesc = "Able to take pictures with it.", LongDesc = "A camera is an optical instrument for capturing still images or for recording moving images, which are stored in a physical medium such as in a digital system or on photographic film. A camera consists of a lens which focuses light from the scene, and a camera body which holds the image capture mechanism.", ImageUrl = "/images/Details/cam.jpg", ThumbnailUrl = "/images/ChristmasGift.jpg" }
                );

                context.SaveChanges(); 
            }       
        }
    }
}
